name: Checkout a reference
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: jsoref/checkout@logging-for-fetch-fail
        with:
          ref: hello-world
