name: Checkout a reference
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  github-actions-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: hello-world

  alternate-actions-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: jsoref/checkout@logging-for-fetch-fail
        with:
          ref: hello-world
